name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
       - name: Checkout
       - uses: actions/checkout@v2
